### ISSUE TITLE
bug with milestone selectors

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Dark#376]
This is probably pebcak but meh

### Unstyled Content

- [x] No other existing issue and/or pull request.
- [ ] URL of unstyled content.
- [ ] If unable to provide a URL, please report the class name of unstyled content.
- [x] Provide steps to reproduce (opening a dialog, etc).

This Im not sure atm, but it seems to apply only to GitHub Dark, GitHub Dark Script this works OK

see below

![demo-a](https://cloud.githubusercontent.com/assets/3521959/17393420/83b5a1f4-5a1b-11e6-9c04-5b4fa13f03f2.gif)

**Comment by Mottie** [comment]
All fixed now?
