### ISSUE TITLE
WIP: Styling https://github.com/features/actions

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#874]
* **Browser**: ff 65.0.2
* **Operating System**: Win 10 pro
* **Link to page with the issue**:
* **Screenshot before any fixes with GHD**:

![ghd before](https://user-images.githubusercontent.com/31389848/53949741-fb961800-40ca-11e9-887f-58c7341eb625.png)

### Todo:

- [x] Fix actions page missing /*[[bg-choice]]*/
- [x] Fix apply filters to actions page images
- [ ] Fix borders styling on boxes on actions page 
- [ ] Fix before/afters styles on boxes on actions page

**Help with todo list welcome.**

Added these commits.

fix: actions page missing /*[[bg-choice]]*/ [eadd98f](eadd98f6ebfbd7b73535f53e54a8d9ee5c7fe2bd) also improvement on that 99bcfed7a9834490e520298fe2117e67e3fb0b91
fix: apply filters to actions page images [f7d385b](f7d385be42a495736f41a60b06ddcec59a28a651)

Just a few borders to fix, those need to go to autogenerator I think, once i figure them out unless someone gets to it first. :pray: :bowing_man: 

#### A before and after with the 2 commits
![default](https://user-images.githubusercontent.com/31389848/53949915-5c255500-40cb-11e9-9b2b-482d519c0b76.gif)

**Comment by the-j0k3r** [comment]
wasnt able to style the stroke/border colors without breaking something, if anyone knows how please do.
